# TCL File Generated by Component Editor 13.0sp1
# Thu Feb 13 12:31:35 CET 2020
# DO NOT MODIFY


# 
# sqrt_module "sqrt_module" v1.0
# GOD Himself 2020.02.13.12:31:35
# sqrt (x)
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module sqrt_module
# 
set_module_property DESCRIPTION "sqrt (x)"
set_module_property NAME sqrt_module
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Custom Instruction Modules"
set_module_property AUTHOR "GOD Himself"
set_module_property DISPLAY_NAME sqrt_module
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL SQRT
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file sqrt.vhd VHDL PATH sqrt.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter N NATURAL 16 ""
set_parameter_property N DEFAULT_VALUE 16
set_parameter_property N DISPLAY_NAME N
set_parameter_property N TYPE NATURAL
set_parameter_property N UNITS None
set_parameter_property N ALLOWED_RANGES 0:2147483647
set_parameter_property N DESCRIPTION ""
set_parameter_property N HDL_PARAMETER true


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 1
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave done done Output 1
add_interface_port nios_custom_instruction_slave r_out result Output 2*n
add_interface_port nios_custom_instruction_slave X dataa Input 2*n
add_interface_port nios_custom_instruction_slave rst reset Input 1
add_interface_port nios_custom_instruction_slave clk clk Input 1
add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1

